name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        intellijVersion: [ 2023.1.1, 2023.1.2, 2023.1.3, 2023.1.4, 2023.1.5 ]
    runs-on: ubuntu-latest
    name: 'Publish with INTELLIJ ${{ matrix.intellijVersion }}'
    env:
      INTELLIJ_VERSION: ${{ matrix.intellijVersion }}
      INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Evaluate base version
        run: echo "BASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test base version
        run: |
          echo $BASE_VERSION
          echo ${{ env.BASE_VERSION }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run build with gradle
        run: ./gradlew --warning-mode=all build
      - name: Publish plugin
        run: ./gradlew publishPlugin
